package worktree

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/morphis/gummi/internal/domain"
)

// provenanceRe matches agent-authorship metadata in a commit message:
// attribution trailers, "generated by/with" lines, model-versioned names,
// and gummi's own review vocabulary (verdict grammar, %% role markers) —
// the traces a coding agent leaves when it writes commit messages itself.
// Deliberately versioned/structured forms only: a commit legitimately
// about, say, Copilot integration must not trip it on a bare product name.
var provenanceRe = regexp.MustCompile(`(?im)(` +
	`^\s*co-authored-by:.*$` +
	`|generated (with|by)\b` +
	`|🤖` +
	`|\bclaude[- ](haiku|sonnet|opus|fable|code|\d)` +
	`|\bgpt-\d` +
	`|\bVERDICT:\s*(pass|changes)\b` +
	`|%%\s*@(reviewer|architect|implementer|scribe)\b` +
	`)`)

// MatchesAttribution returns the first provenance match found in s (the
// matched text, "" when s is clean). It backs both the branch warning scan
// and the squash landing-message scrub, so a generated message can never
// carry agent-authorship metadata into main's history on ctrl+s.
func MatchesAttribution(s string) string {
	return provenanceRe.FindString(s)
}

// Commit is one commit on the feature branch, surfaced to the scribe as
// its short hash and full message. The body may contain any text git
// allows; it is fed to the scribe, never rendered to a terminal.
type Commit struct {
	Hash string
	Body string
}

// BranchCommits returns the feature branch's own commits (merge base to
// tip) in git-log order, one Commit per commit. This is the single
// source of the merge-base/log plumbing; ProvenanceWarnings scans the
// same stream.
func (m *Manager) BranchCommits(ctx context.Context, f *domain.Feature) ([]Commit, error) {
	_, branch, err := m.featurePaths(f)
	if err != nil {
		return nil, err
	}
	base, err := runGit(ctx, m.repo, "merge-base", "HEAD", branch)
	if err != nil {
		return nil, err
	}
	// %x1e separates commits, %x1f the hash from the body — both bytes
	// cannot appear in git object text.
	out, err := runGit(ctx, m.repo, "log", "--format=%h%x1f%B%x1e", base+".."+branch)
	if err != nil {
		return nil, err
	}
	var commits []Commit
	for _, rec := range strings.Split(out, "\x1e") {
		hash, body, ok := strings.Cut(strings.TrimSpace(rec), "\x1f")
		if !ok {
			continue
		}
		commits = append(commits, Commit{Hash: hash, Body: body})
	}
	return commits, nil
}

// draftCommitCap and draftDiffstatMax bound what feeds the landing-message
// scribe pass: branch bodies and a big diff stat must not blow a scribe's
// configured output_token_max on a long feature.
const (
	draftCommitCap   = 50
	draftDiffstatMax = 4000
)

// draftStyleLogWindow, styleSubjectCap, and styleSubjectBytesMax bound the
// main-history style examples in the draft feed: a comfortable git-log
// window is trimmed newest-first to at most styleSubjectCap subjects
// totaling at most styleSubjectBytesMax bytes — enough to show the repo's
// scope vocabulary and subject shape without doubling the prompt size.
const (
	draftStyleLogWindow  = 50
	styleSubjectCap      = 15
	styleSubjectBytesMax = 1200
)

// DraftFeed is the branch material the scribe reads to compose a landing
// commit message: the branch's own commit messages (capped), a bounded
// diffstat against main, and the repo's recent landing-commit subjects
// (capped) as the style examples the message should imitate. All are
// bounded here, beside the git plumbing.
type DraftFeed struct {
	Commits       []Commit
	Diffstat      string
	StyleSubjects []string
}

// BranchDraftFeed returns the branch commits (first draftCommitCap), a
// bounded diffstat (merge base..tip), and main's recent landing-commit
// subjects for the landing-message pass. The diffstat and style subjects
// are advisory: a failure yields an empty field, never a hard error, so
// an unusable stat or history still lets the pass run.
func (m *Manager) BranchDraftFeed(ctx context.Context, f *domain.Feature) (*DraftFeed, error) {
	commits, err := m.BranchCommits(ctx, f)
	if err != nil {
		return nil, err
	}
	if len(commits) > draftCommitCap {
		commits = commits[:draftCommitCap]
	}
	stat, _ := m.branchDiffstat(ctx, f)
	if len(stat) > draftDiffstatMax {
		stat = stat[:draftDiffstatMax]
	}
	return &DraftFeed{
		Commits:       commits,
		Diffstat:      stat,
		StyleSubjects: m.mainStyleSubjects(ctx),
	}, nil
}

// mainStyleSubjects returns the main checkout's most recent commit
// subjects, newest first, capped at styleSubjectCap subjects and
// styleSubjectBytesMax bytes total. They are the landing-style examples
// the scribe imitates — always current, derived from the repo's own
// history at draft time, never configured. Advisory like the diffstat:
// any git failure returns nil, so a sparse or unreadable history simply
// omits the style examples and the prompt degrades to the generic
// Conventional Commits floor instead of failing the pass.
func (m *Manager) mainStyleSubjects(ctx context.Context) []string {
	out, err := runGit(ctx, m.repo, "log", "-n", strconv.Itoa(draftStyleLogWindow),
		"--format=%s", "HEAD")
	if err != nil {
		return nil
	}
	var subjects []string
	total := 0
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" {
			continue
		}
		if len(subjects) == styleSubjectCap || total+len(line)+1 > styleSubjectBytesMax {
			continue
		}
		subjects = append(subjects, line)
		total += len(line) + 1
	}
	return subjects
}

// branchDiffstat returns the diffstat of the feature branch's commits
// against main (merge base..tip).
func (m *Manager) branchDiffstat(ctx context.Context, f *domain.Feature) (string, error) {
	_, branch, err := m.featurePaths(f)
	if err != nil {
		return "", err
	}
	base, err := runGit(ctx, m.repo, "merge-base", "HEAD", branch)
	if err != nil {
		return "", err
	}
	return runGit(ctx, m.repo, "diff", "--stat", base+".."+branch)
}

// ProvenanceWarnings scans the feature branch's own commit messages
// (merge base to tip) for agent-authorship metadata. The squash landing
// discards branch messages — the user writes the landing message — so
// this is belt-and-suspenders: it surfaces attribution that would leak
// if the branch were merged some other way, or that signals an agent
// authored commits it shouldn't have. One warning per offending commit;
// empty when clean.
func (m *Manager) ProvenanceWarnings(ctx context.Context, f *domain.Feature) ([]string, error) {
	commits, err := m.BranchCommits(ctx, f)
	if err != nil {
		return nil, err
	}
	var warns []string
	for _, c := range commits {
		if match := MatchesAttribution(c.Body); match != "" {
			match = strings.TrimSpace(match)
			if len(match) > 40 {
				match = match[:40] + "…"
			}
			warns = append(warns, fmt.Sprintf("%s (%q)", c.Hash, match))
		}
	}
	return warns, nil
}
