package worktree

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/morphis/gummi/internal/domain"
)

// provenanceRe matches agent-authorship metadata in a commit message:
// attribution trailers, "generated by/with" lines, model-versioned names,
// and gummi's own review vocabulary (verdict grammar, %% role markers) —
// the traces a coding agent leaves when it writes commit messages itself.
// Deliberately versioned/structured forms only: a commit legitimately
// about, say, Copilot integration must not trip it on a bare product name.
var provenanceRe = regexp.MustCompile(`(?im)(` +
	`^\s*co-authored-by:.*$` +
	`|generated (with|by)\b` +
	`|🤖` +
	`|\bclaude[- ](haiku|sonnet|opus|fable|code|\d)` +
	`|\bgpt-\d` +
	`|\bVERDICT:\s*(pass|changes)\b` +
	`|%%\s*@(reviewer|architect|implementer|scribe)\b` +
	`)`)

// ProvenanceWarnings scans the feature branch's own commit messages
// (merge base to tip) for agent-authorship metadata. The squash landing
// discards branch messages — the user writes the landing message — so
// this is belt-and-suspenders: it surfaces attribution that would leak
// if the branch were merged some other way, or that signals an agent
// authored commits it shouldn't have. One warning per offending commit;
// empty when clean.
func (m *Manager) ProvenanceWarnings(ctx context.Context, f *domain.Feature) ([]string, error) {
	_, branch, err := m.featurePaths(f)
	if err != nil {
		return nil, err
	}
	base, err := runGit(ctx, m.root, "merge-base", "HEAD", branch)
	if err != nil {
		return nil, err
	}
	// %x1e separates commits, %x1f the hash from the body — both bytes
	// cannot appear in git object text.
	out, err := runGit(ctx, m.root, "log", "--format=%h%x1f%B%x1e", base+".."+branch)
	if err != nil {
		return nil, err
	}
	var warns []string
	for _, rec := range strings.Split(out, "\x1e") {
		hash, body, ok := strings.Cut(strings.TrimSpace(rec), "\x1f")
		if !ok {
			continue
		}
		if match := provenanceRe.FindString(body); match != "" {
			match = strings.TrimSpace(match)
			if len(match) > 40 {
				match = match[:40] + "…"
			}
			warns = append(warns, fmt.Sprintf("%s (%q)", hash, match))
		}
	}
	return warns, nil
}
