package agent

import "encoding/json"

// pi_extension.go carries the pi extension that gives pi's sessions gummi's
// tools over MCP. pi has no native MCP client and no native client-tool
// surface (SessionOpts.Tools) of its own; what it does have is extensions —
// TypeScript files loaded with --extension that may register arbitrary
// tools on the session. So the adapter materializes this file per session
// (it is a generated artifact, like opencode's per-session config) with the
// session's tool descriptors baked in, and the tools register synchronously
// at load — before pi builds the first turn's system prompt, which an async
// tools/list would race. The `gummi __mcp` child is dialed lazily on the
// first tool call, speaking this package's own mcp.Server shim: JSON-RPC
// 2.0, line-delimited, initialize/tools-call, protocol version 2025-06-18 —
// the same surface every other MCP-backed adapter (claude, codex, opencode)
// reaches through their native transports. A session whose opts carry no
// tools (the board-level hosted one) falls back to a live tools/list over
// the child instead.

// piMCPConfig is the baked-in config of one generated extension: the child
// command it spawns, the environment the child needs, and the tool
// descriptors (the same ToolDefs the engine hands every MCP-bound session).
type piMCPConfig struct {
	Cmd   string            `json:"cmd"`
	Args  []string          `json:"args"`
	Env   map[string]string `json:"env"`
	Tools []piMCPTool       `json:"tools,omitempty"`
}

// piMCPTool is one baked tool descriptor; Parameters is the tool's JSON
// Schema (a plain map, adapter-agnostic).
type piMCPTool struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	Parameters  map[string]any `json:"parameters,omitempty"`
}

// piMCPToolFromDefs converts the engine's ToolDefs into the baked
// descriptor shape.
func piMCPToolFromDefs(tools []ToolDef) []piMCPTool {
	out := make([]piMCPTool, 0, len(tools))
	for _, t := range tools {
		out = append(out, piMCPTool(t))
	}
	return out
}

// buildPiExtension renders the per-session extension source. The gate
// mirrors buildGummiMCPServerConfig's: a socket with neither a feature id
// nor the Workspace flag is unbound — the one case that must stay toolless
// (a transient session) — and workspace selects ["__mcp","--workspace"]
// with featureID never consulted.
func buildPiExtension(execPath, featureID, sockPath string, workspace bool, tools []piMCPTool) ([]byte, error) {
	if sockPath == "" || (featureID == "" && !workspace) {
		return nil, nil
	}
	args := []string{"__mcp", "--feature", featureID}
	if workspace {
		args = []string{"__mcp", "--workspace"}
	}
	cfg, err := json.Marshal(piMCPConfig{
		Cmd:   execPath,
		Args:  args,
		Env:   map[string]string{"GUMMI_MCP_SOCK": sockPath},
		Tools: tools,
	})
	if err != nil {
		// The value is a fixed shape of strings/slices/maps; json.Marshal
		// cannot fail on it, so a panic here would only mask a
		// programming error.
		panic(err)
	}
	return append(append([]byte(piExtensionPreamble+"const CFG = "), cfg...), append([]byte(";\n\n"), piExtensionBody...)...), nil
}

const piExtensionPreamble = `// gummi's tools for pi. GENERATED by gummi (internal/agent/pi_extension.go) —
// edit gummi, not this file. The session's tool descriptors are baked in
// below (TOOLS) and register synchronously at load, so the very first
// prompt sees them; the gummi MCP child is dialed lazily on the first tool
// call. Tool failures surface as thrown errors (pi reports them to the
// model with isError set); a failed connection never breaks the session.
import { spawn } from "node:child_process";

`

// piExtensionBody is the extension logic, minus the config line the builder
// injects ahead of it. Tool failures are signaled by throwing from execute —
// pi catches a thrown error and reports it to the model with isError set;
// a returned value never sets the error flag, no matter what it contains.
// No template literals: the source lives in Go raw strings.
const piExtensionBody = `const BAKED = CFG && Array.isArray(CFG.tools) ? CFG.tools : [];
const seenNames = new Set();
const pending = new Map();
let child = null;
let seq = 0;
let streamErr = null;
let ready = null;

function handleFrame(line) {
    let frame;
    try {
        frame = JSON.parse(line);
    } catch (err) {
        return; // not a JSON-RPC frame: nothing to correlate
    }
    const id = frame.id === undefined || frame.id === null ? "" : String(frame.id);
    const entry = pending.get(id);
    if (!entry) {
        return; // a notification, or a response whose caller is gone
    }
    pending.delete(id);
    if (frame.error) {
        entry.reject(new Error("gummi: " + (frame.error.message || "rpc error")));
    } else {
        entry.resolve(frame.result);
    }
}

function spawnChild() {
    child = spawn(CFG.cmd, CFG.args, {
        env: Object.assign({}, process.env, CFG.env),
        stdio: ["pipe", "pipe", "pipe"],
    });
    let buffer = "";
    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
        buffer += chunk;
        let idx = buffer.indexOf("\n");
        while (idx >= 0) {
            const line = buffer.slice(0, idx).replace(/\r$/, "");
            buffer = buffer.slice(idx + 1);
            if (line) {
                handleFrame(line);
            }
            idx = buffer.indexOf("\n");
        }
    });
    child.stderr.on("data", () => {}); // drained; diagnostics surface as call failures
    child.on("exit", (code) => {
        const err = new Error("gummi tool server exited (status " + code + ")");
        for (const entry of pending.values()) {
            entry.reject(err);
        }
        pending.clear();
        // a dead child resets its state so the next call retries fresh —
        // a re-dial is an optimization, never a way to wedge the session
        ready = null;
        streamErr = null;
        child = null;
    });
    child.on("error", (err) => {
        if (!streamErr) {
            streamErr = err;
        }
    });
}

// connect dials the gummi MCP child once, lazily, and resolves after the
// initialize handshake.
function connect() {
    if (ready) {
        return ready;
    }
    ready = new Promise((resolve, reject) => {
        spawnChild();
        request("initialize", {
            protocolVersion: "2025-06-18",
            capabilities: {},
            clientInfo: { name: "gummi-pi-extension", version: "1" },
        })
            .then(() => {
                child.stdin.write(JSON.stringify({
                    jsonrpc: "2.0",
                    method: "notifications/initialized",
                    params: {},
                }) + "\n");
                resolve();
            })
            .catch(reject);
    });
    return ready;
}

function callTool(name, args, signal) {
    return connect()
        .then(() => request("tools/call", { name, arguments: args }, signal))
        .then((result) => ({ text: firstText(result), isError: !!(result && result.isError) }));
}

function request(method, params, signal) {
    if (streamErr) {
        return Promise.reject(streamErr);
    }
    return new Promise((resolve, reject) => {
        const id = String(++seq);
        pending.set(id, { resolve, reject });
        if (signal) {
            signal.addEventListener("abort", () => {
                pending.delete(id);
                reject(new Error("gummi tool call aborted"));
            }, { once: true });
        }
        child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id: Number(id), method, params }) + "\n");
    });
}

function firstText(result) {
    if (result && Array.isArray(result.content)) {
        for (const block of result.content) {
            if (block && block.type === "text" && typeof block.text === "string") {
                return block.text;
            }
        }
    }
    return "";
}

function diag(err) {
    const msg = err && err.message ? err.message : String(err);
    process.stderr.write("gummi tools unavailable: " + msg + "\n");
}

function registerTools(pi, tools) {
    for (const tool of tools) {
        if (!tool || !tool.name || seenNames.has(tool.name)) {
            continue;
        }
        seenNames.add(tool.name);
        pi.registerTool({
            name: tool.name,
            label: tool.name,
            description: tool.description || "gummi tool",
            parameters: tool.parameters || tool.inputSchema || { type: "object", properties: {} },
            execute: (toolCallId, params, signal) =>
                callTool(tool.name, params || {}, signal).then((res) => {
                    if (res.isError) {
                        throw new Error(res.text);
                    }
                    return { content: [{ type: "text", text: res.text }], details: {} };
                }),
        });
    }
}

export default function gummiTools(pi) {
    // The stage's tool descriptors ride the generated file: they register
    // synchronously, before pi builds the first turn's system prompt.
    registerTools(pi, BAKED);
    // A session with no baked tools (the board-level hosted one) discovers
    // its tools live over the child instead. This races nothing: it
    // registers whenever the child comes up, and a board agent converses
    // before it calls.
    if (BAKED.length === 0) {
        connect()
            .then(() => request("tools/list", {}))
            .then((result) => {
                const tools = result && Array.isArray(result.tools) ? result.tools : [];
                registerTools(pi, tools);
                if (tools.length === 0) {
                    process.stderr.write("gummi tools: the session's tool set is empty\n");
                }
            })
            .catch(diag);
    }
}
`
